<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PriceList;

class PriceListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $priceListData = [
            // PLN Products
            [
                'brand' => 'PLN',
                'product_name' => 'PLN Token 20K',
                'price' => 22500.00,
                'original_price' => 20000.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'PLN20',
                'desc' => 'PLN Token Listrik Prabayar 20.000',
                'category' => 'PLN',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'prepaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 1500.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'prepaid',
                'profit_type' => 'fixed',
                'profit_margin' => 0.00,
                'fixed_profit' => 1500.00,
                'last_updated' => now(),
            ],
            [
                'brand' => 'PLN',
                'product_name' => 'PLN Token 50K',
                'price' => 52500.00,
                'original_price' => 50000.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'PLN50',
                'desc' => 'PLN Token Listrik Prabayar 50.000',
                'category' => 'PLN',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'prepaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 2000.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'prepaid',
                'profit_type' => 'fixed',
                'profit_margin' => 0.00,
                'fixed_profit' => 1500.00,
                'last_updated' => now(),
            ],
            [
                'brand' => 'PLN',
                'product_name' => 'PLN Token 100K',
                'price' => 102500.00,
                'original_price' => 100000.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'PLN100',
                'desc' => 'PLN Token Listrik Prabayar 100.000',
                'category' => 'PLN',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'prepaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 2000.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'prepaid',
                'profit_type' => 'fixed',
                'profit_margin' => 0.00,
                'fixed_profit' => 500.00,
                'last_updated' => now(),
            ],
            // Telkomsel Products
            [
                'brand' => 'Telkomsel',
                'product_name' => 'Telkomsel 5GB 30 Hari',
                'price' => 35000.00,
                'original_price' => 32000.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'TSEL5GB',
                'desc' => 'Paket Data Telkomsel 5GB 30 Hari',
                'category' => 'Data',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'prepaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 2500.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'prepaid',
                'profit_type' => 'fixed',
                'profit_margin' => 0.00,
                'fixed_profit' => 500.00,
                'last_updated' => now(),
            ],
            [
                'brand' => 'Telkomsel',
                'product_name' => 'Telkomsel 10GB 30 Hari',
                'price' => 55000.00,
                'original_price' => 50000.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'TSEL10GB',
                'desc' => 'Paket Data Telkomsel 10GB 30 Hari',
                'category' => 'Data',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'prepaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 4000.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'prepaid',
                'profit_type' => 'fixed',
                'profit_margin' => 0.00,
                'fixed_profit' => 1000.00,
                'last_updated' => now(),
            ],
            // Gaming Voucher Products
            [
                'brand' => 'Steam',
                'product_name' => 'Steam Wallet 50.000',
                'price' => 55000.00,
                'original_price' => 52000.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'STEAM50',
                'desc' => 'Steam Wallet IDR 50.000',
                'category' => 'Voucher Game',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'prepaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 2500.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'prepaid',
                'profit_type' => 'fixed',
                'profit_margin' => 0.00,
                'fixed_profit' => 500.00,
                'last_updated' => now(),
            ],
            [
                'brand' => 'Google Play',
                'product_name' => 'Google Play Gift Card 50.000',
                'price' => 52500.00,
                'original_price' => 50000.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'GPLAY50',
                'desc' => 'Google Play Gift Card IDR 50.000',
                'category' => 'Voucher Game',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'prepaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 2000.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'prepaid',
                'profit_type' => 'fixed',
                'profit_margin' => 0.00,
                'fixed_profit' => 500.00,
                'last_updated' => now(),
            ],
            // Postpaid Products
            [
                'brand' => 'PLN',
                'product_name' => 'PLN Postpaid',
                'price' => 0.00,
                'original_price' => 0.00,
                'buyer_product_status' => true,
                'seller_product_status' => true,
                'buyer_sku_code' => 'PLNPOST',
                'desc' => 'Pembayaran Tagihan PLN Postpaid',
                'category' => 'PLN',
                'seller_name' => 'DIGIFLAZZ',
                'type' => 'postpaid',
                'unlimited_stock' => true,
                'stock' => 999999,
                'multi' => false,
                'start_cut_off' => '00:00:00',
                'end_cut_off' => '23:59:00',
                'admin' => 2500.00,
                'commission' => 0.00,
                'admin_fee' => 1000.00,
                'product_type' => 'postpaid',
                'profit_type' => 'percentage',
                'profit_margin' => 2.5,
                'fixed_profit' => 0.00,
                'last_updated' => now(),
            ],
        ];

        foreach ($priceListData as $item) {
            PriceList::create($item);
        }
    }
}
